### ISSUE TITLE
./build.sh Fails to Croak When No Ruby

### ISSUE THREAD

**Issue by jlpoolen** [p-gen/hlvt#2]
I do not have Ruby installed (but I will install it shortly):

> jlpoole@themis /usr/local/src/hlvt $ ./build.sh
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether make supports nested variables... (cached) yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for style of include used by make... GNU
> checking dependency style of gcc... gcc3
> checking for ruby... no
> checking for ruby20... no
> checking for ruby21... no
> checking for ruby22... no
> checking for ruby23... no
> checking for ruby24... no
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for stdlib.h... (cached) yes
> checking for string.h... (cached) yes
> checking for unistd.h... (cached) yes
> checking for size_t... yes
> checking for stdlib.h... (cached) yes
> checking for GNU libc compatible malloc... yes
> checking for stdlib.h... (cached) yes
> checking for GNU libc compatible realloc... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating config.h
> config.status: executing depfiles commands
> make  all-am
> make[1]: Entering directory '/usr/local/src/hlvt'
> vtparse_gen_c_tables.rb
> make[1]: vtparse_gen_c_tables.rb: Command not found
> make[1]: *** [Makefile:743: vtparse_table.c] Error 127
> make[1]: Leaving directory '/usr/local/src/hlvt'
> make: *** [Makefile:273: all] Error 2
> jlpoole@themis /usr/local/src/hlvt $

Although the build.sh failed, it would be better to have it fail at the test point for Ruby rather than letting the user discern that "Command not found" on an .rb script means Ruby is not installed.

**Comment by p-gen** [comment]
Yes, I will do that, although the need for ruby ​​is clearly stated at the end of the README.

Thank you for reporting.

**Comment by p-gen** [comment]
Fixed by commit 8d159b4. If ruby is not installed, pre-built files will be used.
